#!/usr/bin/env bash
# Binance USDT-M Futures Trading Bot — interactive installer.
# Idempotent: safe to re-run. Use --force to overwrite an existing .env/config.yaml.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
cd "$SCRIPT_DIR"

FORCE=0
for arg in "$@"; do
    case "$arg" in
        -f|--force) FORCE=1 ;;
        -h|--help)
            cat <<EOF
Usage: ./install.sh [--force]

Creates a Python venv, installs dependencies, and interactively asks for:
  - Binance API key / secret
  - Telegram bot token / chat id
  - Default run mode (sim | live)

Writes .env (chmod 600) and config.yaml. Re-run with --force to overwrite.
EOF
            exit 0 ;;
    esac
done

color() { printf '\033[%sm%s\033[0m' "$1" "$2"; }
info()  { echo "$(color '1;34' '[*]') $*"; }
warn()  { echo "$(color '1;33' '[!]') $*"; }
ok()    { echo "$(color '1;32' '[✓]') $*"; }
err()   { echo "$(color '1;31' '[x]') $*" >&2; }

# --- 1. Python version check ------------------------------------------------
info "Checking Python..."
if ! command -v python3 >/dev/null 2>&1; then
    err "python3 not found. Install Python 3.11+ and re-run."
    exit 1
fi

PY_VER=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')
PY_MAJOR=$(python3 -c 'import sys; print(sys.version_info[0])')
PY_MINOR=$(python3 -c 'import sys; print(sys.version_info[1])')
if [ "$PY_MAJOR" -lt 3 ] || { [ "$PY_MAJOR" -eq 3 ] && [ "$PY_MINOR" -lt 11 ]; }; then
    err "Python >= 3.11 required (found $PY_VER)."
    exit 1
fi
ok "Python $PY_VER"

# --- 2. venv ----------------------------------------------------------------
if [ ! -d ".venv" ]; then
    info "Creating virtualenv at .venv ..."
    if ! python3 -m venv .venv 2>/dev/null; then
        warn "python3 -m venv failed — you may need to install python3-venv"
        warn "On Debian/Ubuntu: sudo apt install python3-venv"
        exit 1
    fi
    ok "venv created"
else
    ok "venv exists"
fi

# shellcheck disable=SC1091
source .venv/bin/activate

info "Upgrading pip..."
pip install --upgrade pip >/dev/null
info "Installing dependencies (this may take a minute)..."
pip install -r requirements.txt
ok "dependencies installed"

# --- 3. config.yaml ---------------------------------------------------------
if [ -f "config.yaml" ] && [ "$FORCE" -eq 0 ]; then
    ok "config.yaml already present (use --force to overwrite)"
else
    cp config.example.yaml config.yaml
    ok "config.yaml created from config.example.yaml"
fi

# --- 4. .env prompt ---------------------------------------------------------
if [ -f ".env" ] && [ "$FORCE" -eq 0 ]; then
    ok ".env already present (use --force to re-prompt)"
else
    echo
    info "Let's set up your credentials."
    echo "   (Press Enter to leave a field blank and fill it in later by editing .env.)"
    echo

    read -rp "   Binance API Key: " BINANCE_API_KEY
    read -rsp "   Binance API Secret: " BINANCE_API_SECRET
    echo
    read -rp "   Use Binance Futures TESTNET? [y/N]: " USE_TESTNET
    TESTNET_VAL="false"
    case "${USE_TESTNET:-}" in
        y|Y|yes|YES) TESTNET_VAL="true" ;;
    esac

    read -rsp "   Telegram Bot Token (from @BotFather): " TG_TOKEN
    echo
    read -rp "   Telegram Chat ID (numeric, from @userinfobot): " TG_CHAT

    DEFAULT_MODE="sim"
    read -rp "   Default run mode [sim/live] (default sim): " MODE_IN
    case "${MODE_IN:-}" in
        live|LIVE) DEFAULT_MODE="live" ;;
        *) DEFAULT_MODE="sim" ;;
    esac

    umask 077
    cat > .env <<EOF
# Auto-generated by install.sh. Edit as needed.
BINANCE_API_KEY=${BINANCE_API_KEY}
BINANCE_API_SECRET=${BINANCE_API_SECRET}
BINANCE_TESTNET=${TESTNET_VAL}

TELEGRAM_BOT_TOKEN=${TG_TOKEN}
TELEGRAM_CHAT_ID=${TG_CHAT}

RUN_MODE=${DEFAULT_MODE}
EOF
    chmod 600 .env
    ok ".env written (chmod 600)"
fi

# --- 5. make run.sh executable ---------------------------------------------
chmod +x run.sh 2>/dev/null || true

# --- 6. smoke-check imports ------------------------------------------------
info "Verifying imports..."
if python3 -c "import src.config, src.bot, src.exchange.simulator, src.strategy.trend_momentum" 2>/dev/null; then
    ok "imports OK"
else
    warn "import check failed — run 'python3 -c \"import src.bot\"' to debug"
fi

cat <<'EOF'

──────────────────────────────────────────────
 ✅ Install complete.

 Next steps:

   ./run.sh                # runs in mode from .env (defaults to sim)
   ./run.sh --mode sim     # force simulation (paper trading, no real orders)
   ./run.sh --mode live    # real orders on Binance Futures — READ THE DOCS FIRST

 Edit strategy parameters:  config.yaml
 Edit credentials:          .env
──────────────────────────────────────────────
EOF
